### ISSUE TITLE
the network unstake error

### ISSUE THREAD

**Issue by mingxingmeng** [REI-Network/rei-scan#13]
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x26a89dd06d9e74e9724d8ac52cc240c2a560b481c1a4067cd2ee8a74b44a2958",
  "blockNumber": 16271180,
  "contractAddress": null,
  "cumulativeGasUsed": 74548,
  "from": "0xb93dbad3493767e7a5ff069e3e349a0901e745d7",
  "gasUsed": 74548,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x0000000000000000000000000000000000001001",
  "transactionHash": "0x9472d4873be32c581faff9c33982deececade1cc3f3b668d6c6c7dd448207d30",
  "transactionIndex": 0,
  "events": {
    "0": {
      "address": "0x0000000000000000000000000000000000001005",
      "blockHash": "0x26a89dd06d9e74e9724d8ac52cc240c2a560b481c1a4067cd2ee8a74b44a2958",
      "blockNumber": 16271180,
      "logIndex": 0,
      "removed": false,
      "transactionHash": "0x9472d4873be32c581faff9c33982deececade1cc3f3b668d6c6c7dd448207d30",
      "transactionIndex": 0,
      "id": "log_910ab458",
      "returnValues": {},
      "signature": null,
      "raw": {
        "data": "0x",
        "topics": [
          "0x873c82cd37aaacdcf736cbb6beefc8da36d474b65ad23aaa1b1c6fbd875f7076",
          "0x0000000000000000000000000000000000000000000000000000000000000000",
          "0x000000000000000000000000000000000000000000000000000043cd0f0f0800"
        ]
      }
    }
  }
}
    at Object.TransactionError (chunk-vendors.674fc1ba.js:60:1129535)
    at Object.TransactionRevertedWithoutReasonError (chunk-vendors.674fc1ba.js:60:1129907)
    at chunk-vendors.674fc1ba.js:60:1145992
    at d (chunk-vendors.674fc1ba.js:60:1269306)
    at Generator.<anonymous> (chunk-vendors.674fc1ba.js:60:1270661)
    at Generator.next (chunk-vendors.674fc1ba.js:60:1269669)
    at t (chunk-vendors.674fc1ba.js:60:1263709)
    at s (chunk-vendors.674fc1ba.js:60:1263920)
    at chunk-vendors.674fc1ba.js:60:1263979
    at new Promise (<anonymous>)

**Comment by mingxingmeng** [comment]
REI address
0xB93dBAd3493767E7a5fF069E3e349A0901E745d7
